### ISSUE TITLE
mac下客户端的报错

### ISSUE THREAD

**Issue by koyabr** [Leviathan1995/fari-proxy#9]
操作系统: macOS 10.12.6
客户端版本: 0.4

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x10cae82]

goroutine 5 [running]:
github.com/fari-proxy/encryption.(*Cipher).BlockSize(0xc420010600, 0xc42003bd90)
	<autogenerated>:1 +0x32
crypto/cipher.newCFB(0x11ffa40, 0xc420010600, 0xc42001c360, 0x10, 0x10, 0x129b000, 0x0, 0x108b941)
	/usr/local/go/src/crypto/cipher/cfb.go:57 +0x3b
crypto/cipher.NewCFBEncrypter(0x11ffa40, 0xc420010600, 0xc42001c360, 0x10, 0x10, 0xc420090001, 0xc42001c410)
	/usr/local/go/src/crypto/cipher/cfb.go:46 +0x58
github.com/fari-proxy/encryption.(*Cipher).AesEncrypt(0xc420010600, 0xc42001c410, 0x3, 0x3, 0xc420080800, 0x3, 0x800, 0xc42001c360, 0x10, 0x10, ...)
	/Users/leviathan/code/gowork/src/github.com/fari-proxy/encryption/aesCFB.go:23 +0x62
github.com/fari-proxy/service.(*Service).Encode(0xc42000c240, 0xc42000e060, 0xc420080800, 0x3, 0x800, 0x0, 0x0, 0x110ae12)
	/Users/leviathan/code/gowork/src/github.com/fari-proxy/service/service.go:57 +0x110
github.com/fari-proxy/service.(*Service).EncodeTransfer(0xc42000c240, 0xc42000e060, 0xc42000e050, 0xc42000e050, 0xc42000e060)
	/Users/leviathan/code/gowork/src/github.com/fari-proxy/service/service.go:88 +0x12f
github.com/fari-proxy/client/util.(*client).handleConn(0xc42000e038, 0xc42000e050)
	/Users/leviathan/code/gowork/src/github.com/fari-proxy/client/util/client.go:66 +0x167
created by github.com/fari-proxy/client/util.(*client).Listen
	/Users/leviathan/code/gowork/src/github.com/fari-proxy/client/util/client.go:42 +0x26e
```

**Comment by Leviathan1995** [comment]
@koyabr 我这边Mac客户端测试没发现问题，我的系统是10.13.1

**Comment by Leviathan1995** [comment]
@koyabr 你那边还是不可以？

**Comment by koyabr** [comment]
@Leviathan1995 可能是密码强度不够？我换了一个更长的密码就正常了

**Comment by Leviathan1995** [comment]
非常感谢，这个问题我留意一下

koyabr <notifications@github.com>于2017年11月5日 周日下午10:31写道：
